name: ci/release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        export POETRY_HOME=/opt/poetry
        python -m pip install --upgrade pip setuptools
        python -m pip install poetry
        poetry install --only dev
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        rm -rf dist/*
        poetry run python setup.py sdist bdist_wheel
        poetry run twine upload dist/*